name: vector_workspace
publish_to: none

environment:
  sdk: ^3.10.0

workspace:
  - apps/vector
  - packages/domain
  - packages/core
  - packages/data

dev_dependencies:
  melos: ^7.3.0
  very_good_analysis: ^10.0.0

#####
melos:
  name: vector_monorepo

  scripts:
    analyze:
      run: melos exec -- flutter analyze

    run_dev:
      exec: flutter run --flavor development --target lib/main_development.dart
      packageFilters:
        scope: vector

    format-check:
      run: melos exec -- "dart format . --set-exit-if-changed"
      description: Ensure all code follows standard indentation.
    
    test:
      run: melos exec --dir-exists="test" -- "flutter test"
      description: Run all Flutter tests in packages that have a "test" directory.