name: vector
description: A Crypto Price Tracker
version: 1.0.2+3
publish_to: none
resolution: workspace


environment:
  sdk: ^3.10.0
  flutter: ^3.38.1

dependencies:
  bloc: ^9.2.0
  core:
    path: ../../packages/core
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^9.1.1
  injectable: ^2.7.0
  intl: ^0.20.2
  vector_data:
    path: ../../packages/data
  vector_domain:
    path: ../../packages/domain
  

dev_dependencies:
  bloc_lint: ">=0.3.3 <0.3.6"
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.20
  build_runner: ^2.10.5
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.12.1
  mocktail: ^1.0.4
  very_good_analysis: ^10.1.0

flutter:
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  ios: false
  image_path_ios: "assets/images/vector_app_icon.png"
  
  android: "launcher_icon"
  image_path_android: "assets/images/vector_app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/vector_app_icon_transparent.png"
