name: Vector CI/CD

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  quality_gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Melos
        run: dart pub global activate melos

      - name: Bootstrap Workspace
        run: melos bootstrap

      - name: Static Analysis (All Packages)
        run: melos run analyze
      
      - name: Verify Formatting (Indentation)
        run: melos run format-check
      
      - name: Unit & Widget Tests
        run: melos run test --no-select


  build_android:
    needs: quality_gate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      
      - name: Install Melos
        run: dart pub global activate melos

      - name: Bootstrap
        run: melos bootstrap

      - name: Generate production env file
        run: |
          cd apps/vector
          cat > env/prod.json <<EOF
          {
            "BASE_URL": "https://api.coingecko.com/api/v3",
            "COINGECKO_API_KEY": "${{ secrets.COINGECKO_API_KEY }}",
            "ENABLE_LOGGING": false
          }
          EOF

      - name: Build Vector Release(Production) APK
        run: |
          cd apps/vector
          flutter build apk --release \
            --flavor production \
            --target lib/main_production.dart \
            --dart-define-from-file=env/prod.json \
            --tree-shake-icons

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vector-android-release
          path: apps/vector/build/app/outputs/flutter-apk/app-production-release.apk
          if-no-files-found: error


  create_release:
    name: Create GitHub Release
    needs: build_android
    if: startsWith(github.ref, 'refs/tags/v') 
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract App Version
        id: extract_version
        run: |
          VERSION=$(grep '^version: ' apps/vector/pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "app_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: vector-android-release

      - name: Publish Draft Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }} 
          name: Vector Release ${{ github.ref_name }}
          draft: true
          prerelease: false
          generate_release_notes: true
          files: app-production-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}